### ISSUE TITLE
Error polymap.py

### ISSUE THREAD

**Issue by stijnploeg** [brainsmoke/polymap#1]
Hi Brainsmoke, 
The code you wrote is exactly what I need for a hobby project I am doing right now. 
However, I ran your code using Python2 and I got the following error:

Traceback (most recent call last):
  File "./polymap.py", line 305, in <module>
    comment=comment)
  File "./polymap.py", line 182, in render_polyhedron_map
    inkscape_batch_intersection(filename, len(faces), invert)
  File "./polymap.py", line 99, in inkscape_batch_intersection
    os.spawnvp*(os.P_WAIT, 'inkscape', argv)
AttributeError: 'module' object has no attribute 'spawnvp'

I tried an online search to see if I could fix it myself but that did not work out so far. 
I was hoping if you know what I can do to fix it. 

Kind regards
Stijn

PS. The code does make .svg file but it does not look the same as the example posted on the wiki. 
![Screenshot 2021-08-06 132211](https://user-images.githubusercontent.com/37934120/128503247-57c7f05b-0475-4551-b48d-dbc44f91f214.png)

**Comment by brainsmoke** [comment]
Hi Stijn,

Thanks for mentioning that this script still uses python2 :grimacing: I thought I had converted it a long time ago.

It looks like os.spawnvp() is not supported on Windows, so that may be the problem.

The black shapes are groups of two paths, and I'm scripting inkscape to get the path intersection of these two.
I don't know if rewriting it to os.spawnv(os.P_WAIT, '/full/path/to/inkscape.exe', argv)) will work.

I don't have a windows machine to test at the moment. ```subprocess.call(argv)``` may also work, or ```print(argv)``` and pasting the resulting line on the command line.

If that doesn't work and you have a access to a linux machine with inkscape installed I'd try that first :-P.

Another option is to manually edit the SVG you have now: select the groups with black paths and do ctrl-shift g, ctrl-*

Erik.

**Comment by stijnploeg** [comment]
Hey Eric, 

Thanks for the quick response. I am currently to run the code with Ubuntu 20.14 on a virtual machine. 
It now returns the following error: Gtk-Message: Failed to load module "canberra-gtk-module".

**Comment by brainsmoke** [comment]
I think ```Gtk-Message: Failed to load module "canberra-gtk-module"``` is just a warning/debug message and shouldn't be a problem.

Are you running the script from a graphical interface, of via an ssh login? Sadly inkscape needs its UI even for scripted sessions (it will also pop-up and create a screen).

Does starting inkscape in a normal way work?

**Comment by stijnploeg** [comment]
I run the script via the terminal in the virtual machine.
As far as I can tell Inkscape starts in a normal way but I haven't seen anything pop up when running the script. I will try to run it via a GI.

Thnx!

**Comment by stijnploeg** [comment]
Hey Eric,
It works now! I solved it by downloading a older version of Inkscape (0.92.5-1ubuntu1)
Thanks for the help!

Stijn
