### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by BeInspiredWithDominic** [brainsmoke/polymap#3]
I am using cmd on Windows 10 to run this. I never wrote Python myself. Here is what I get:

`python polymap.py -I --radius 160 --centerdot
  File "C:\Users\...\Downloads\polymap-master\polymap.py", line 37
    print "face (%d/%d)" % (i,len(faces))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?`

I added a "(" after "print" and a ")" at the end. Next, I get

`Traceback (most recent call last):
  File "C:\Users\...\Downloads\polymap-master\polymap.py", line 5, in <module>
    import globe, svg, pathedit, projection, linear, polymath, maps
  File "C:\Users\...\Downloads\polymap-master\globe.py", line 108
    def border_node((x1,y1,z1), (x2,y2,z2), z_border):
                    ^
SyntaxError: invalid syntax`

When I load globe.py in Komodo, it marks that line as a syntax error, but I cannot figure out what the error is.
Any help is much appreciated!

**Comment by BeInspiredWithDominic** [comment]
Apparently there's an issue - many issues - since this was written for Python 2. I'm not sure whether fixing them is within my abilities, including getting Python 2 to run on my machine.
